### ISSUE TITLE
MathJax er ikke konfigureret til at håndtere $.

### ISSUE THREAD

**Issue by soegaard** [carsten-j/carsten-j.github.io#1]
Hej Carsten,

Jeg lagde mærke til, at siderne 

https://carsten-j.github.io/2017/08/22/konfidensintervaller.html
https://carsten-j.github.io/2017/10/18/regressionsanalyse.html

ikke viser inline formler markeret med $. 

Du har sandsynligvis opdateret eller ændret din version af MathJax
og misset, at $ ikke længere er med som default.

**Comment by carsten-j** [comment]
Tak for at gøre mig opmærksom på dette. Jeg tror, at jeg har få fikset problemet.
