### ISSUE TITLE
Link i sidefoden

### ISSUE THREAD

**Issue by soegaard** [carsten-j/carsten-j.github.io#2]
Hej,

I sidefoden står der:

<img width="330" alt="image" src="https://github.com/carsten-j/carsten-j.github.io/assets/461765/e33e8124-6520-41da-84fb-729c35f09180">

Klikker man på "Carsten Jørgensen" ender man på:  https://carstenj.io/
og den side ser suspekt ud (har links til sports betting).

**Comment by carsten-j** [comment]
Tak for at gøre mig opmærksom på det. Det bør nu være fikset.

**Comment by soegaard** [comment]
Hej Carsten,

På Github, dvs på

https://github.com/carsten-j/carsten-j.github.io

kan man yderst til højre se samme link:

<img width="222" alt="image" src="https://github.com/carsten-j/carsten-j.github.io/assets/461765/c494e2a5-749b-492b-8a0d-f08cc7e2f805">

Mvh,
Jens Axel

**Comment by carsten-j** [comment]
Tak. Det bør være rettet.
Jeg er glad for dine henvendelser. Må jeg spørge, hvordan du fandt siden og
hvad du har brugt af den?

Vh
Carsten

**Comment by soegaard** [comment]
Jeg var/er ved at skrive en blog-post om konfidensinterval i forbindelse med andel af population.

I den forbindelse fandt jeg din side ved at søge på "konfidensinterval" på Github.

Og så blev jeg lidt nysgerrig - i første omgang troede jeg nemlig du var ansat ved Webmatematik (en af "konkurrenterne").
Dine artikler om konfidensinterval og multipel regression er begge af høj kvalitet (det er ikke en selvfølge på Webmatematik).  Det er en skam, at forfatterne til deres artikler ikke angives ved navn - det ville gøre det nemmere at få rettet uhensigtsmæssigheder. 

Send mig gerne en mail på jensaxel@soegaard.net så sender jeg en pdf-udgave med den foreløbige version.
